"""add_social_access_token

Revision ID: 6a84a3a97b4e
Revises: 8e7851c0ab89
Create Date: 2026-03-20 13:14:49.154381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a84a3a97b4e'
down_revision: Union[str, None] = '8e7851c0ab89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_account', sa.Column('social_access_token', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_account', 'social_access_token')
    # ### end Alembic commands ###
